using System; using System.Collections.ObjectModel; using EAATrainingManager.Models; using EAATrainingManager.Services; using Microsoft.UI.Xaml; using Microsoft.UI.Xaml.Controls;
namespace EAATrainingManager.Views;
public sealed partial class AssessmentsPage : Page
{
 private readonly ObservableCollection<Student> _students=new(); private readonly ObservableCollection<TrainingAssessment> _items=new();
 public AssessmentsPage(){InitializeComponent();StudentCombo.ItemsSource=_students;List.ItemsSource=_items;LocalizationService.Instance.LanguageChanged+=ApplyLocalization;Loaded+=async(_,_)=>{ApplyLocalization();await LoadAsync();};Unloaded+=(_,_)=>LocalizationService.Instance.LanguageChanged-=ApplyLocalization;}
 private async System.Threading.Tasks.Task LoadAsync(){try{await App.DatabaseService.InitializeAsync();var students=await App.DatabaseService.GetAllStudentsAsync();var assessments=await App.DatabaseService.GetTrainingAssessmentsAsync();_students.Clear();foreach(var x in students)_students.Add(x);_items.Clear();foreach(var x in assessments)_items.Add(x);}catch(Exception ex){ErrorText.Text=ex.Message;ErrorText.Visibility=Visibility.Visible;}}
 private async void Save_Click(object s,RoutedEventArgs e){if(StudentCombo.SelectedItem is not Student student){ErrorText.Text=LocalizationService.Instance.Text("اختر متدرباً.","Select a trainee.");ErrorText.Visibility=Visibility.Visible;return;}try{await App.DatabaseService.SaveTrainingAssessmentAsync(new TrainingAssessment{StudentId=student.Id,Title=TitleBox.Text,ExaminerName=ExaminerBox.Text,Result=(ResultCombo.SelectedItem as ComboBoxItem)?.Tag?.ToString()??"Pending",Deficiencies=DeficienciesBox.Text,RemedialPlan=RemedialBox.Text,NextAction=NextActionBox.Text});TitleBox.Text=ExaminerBox.Text=DeficienciesBox.Text=RemedialBox.Text=NextActionBox.Text="";await LoadAsync();}catch(Exception ex){ErrorText.Text=ex.Message;ErrorText.Visibility=Visibility.Visible;}}
 private void ApplyLocalization(){var l=LocalizationService.Instance;FlowDirection=l.CurrentFlowDirection;TitleText.Text=l.Text("التقييمات وبوابات التقدم","Assessments & Progression Gates");DescriptionText.Text=l.Text("توثيق فحوص المراحل والنتائج وخطط المعالجة.","Record stage checks, results, and remedial actions.");AddTitleText.Text=l.Text("تسجيل تقييم","Record assessment");StudentCombo.PlaceholderText=l.Text("المتدرب","Trainee");TitleBox.PlaceholderText=l.Text("اسم التقييم","Assessment title");ExaminerBox.PlaceholderText=l.Text("الفاحص","Examiner");DeficienciesBox.PlaceholderText=l.Text("أوجه القصور","Deficiencies");RemedialBox.PlaceholderText=l.Text("خطة المعالجة","Remedial plan");NextActionBox.PlaceholderText=l.Text("الإجراء التالي","Next action");PendingItem.Content=l.Text("قيد المراجعة","Pending");PassedItem.Content=l.Text("ناجح","Passed");ConditionalItem.Content=l.Text("مشروط","Conditional");FailedItem.Content=l.Text("غير مجتاز","Not passed");SaveButton.Content=l.Text("حفظ التقييم","Save assessment");}
}
